# Workflow File

name: CI

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Build
        run: echo "Building..."